# Generated by Django 4.2 on 2023-04-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=100)),
                ('personMobileNo', models.IntegerField()),
                ('personAddress', models.TextField()),
            ],
        ),
    ]
