# Generated by Django 4.2 on 2023-04-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cal', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategoryFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainStreamFoodName', models.CharField(max_length=100)),
                ('subCategoryFoodCharge', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
